language: node_js
node_js:
  - 0.10
  - 0.12
branches:
  only:
    - test
    - active
    - master
install:
  - npm install
  - npm install -g bon
  - npm install -g batshit # does not install-g bon!
  - export NODE_PATH=$(temp=$(dirname $(which bon)) && echo ${temp//bin/lib\/node_modules})
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
