language: node_js
node_js:
  - 0.10
  - 0.12
branches:
  only:
    - test
    - active
    - master
install:
  - npm install --production  # needed nowhere else, installs the npm dependency, weird npm...
  - npm install
  - npm install -g bon # can skip this one - kept to ensure install-g doesn't break its own tests
  - npm install -g batshit
  - export NODE_PATH=$(bon-p) # needed nowhere else, how is install-g different??
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
